### ISSUE TITLE
Cocoapods, Carthage?

### ISSUE THREAD

**Issue by Prince2k3** [Spinners/Spin.Swift#3]
Do you plan on supporting other dependency managers?

**Comment by twittemb** [comment]
Hi

Yes I’m currently working on it. I’ll keep you posted.

Thanks.

**Comment by twittemb** [comment]
Hi @Prince2k3 

Carthage support has been added in version 0.16.

Cocoapods is next.

**Comment by twittemb** [comment]
Hi @Prince2k3,

Since version 0.16.1, Spin is compatible with CocoaPods.

I close the issue.

Thanks.
